
flib_version=1.0.0-SNAPSHOT

mod_id=mountedpearl
curse_id=232795
curse_slug=mounted-pearl-bring-your-mount-along-when-you
mod_version=1.0.1
mod_name=mountedpearl
mod_group_id=com.lothrazar.mountedpearl
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod
